services:
  - type: web
    name: chichii
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: SUPABASE_URL
        value: https://eemcfihirbziubndronx.supabase.co
      - key: SUPABASE_KEY
        value: sb_publishable_eFM2Ghq8Bu1Eqg36H-0xZA_c5ol1SZd
